// <auto-generated />
using System;
using App_Data_ClassLib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_Data_ClassLib.Migrations
{
    [DbContext(typeof(SD18302_NET104Context))]
    [Migration("20240401125921_SanPham")]
    partial class SanPham
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("App_Data_ClassLib.Models.GioHang", b =>
                {
                    b.Property<Guid>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayThem");

                    b.Property<int>("TongSoLuong")
                        .HasColumnType("int")
                        .HasColumnName("TongSoLuong");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CartID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSPCT")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("CartItemID");

                    b.HasIndex("CartID");

                    b.HasIndex("IDSPCT");

                    b.ToTable("GiohangChiTiet", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.Hang", b =>
                {
                    b.Property<Guid>("IDHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("QuocGia");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHang");

                    b.HasKey("IDHang");

                    b.ToTable("Hang", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.HoaDon", b =>
                {
                    b.Property<Guid>("IDHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HinhThucThanhToan")
                        .HasColumnType("int")
                        .HasColumnName("HinhThucThanhToan");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayMua");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("Decimal")
                        .HasColumnName("TongTien");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDHD");

                    b.HasIndex("UserID");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IDHDCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaSP")
                        .HasColumnType("Decimal")
                        .HasColumnName("GiaSP");

                    b.Property<Guid>("IDHD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKM")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSPCT")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("IDHDCT");

                    b.HasIndex("IDHD");

                    b.HasIndex("IDKM");

                    b.HasIndex("IDSPCT");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.KhuyenMai", b =>
                {
                    b.Property<Guid>("IDKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Giam")
                        .HasColumnType("Decimal")
                        .HasColumnName("Giam");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayKetThuc");

                    b.HasKey("IDKM");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.SanPham", b =>
                {
                    b.Property<Guid>("IDSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.Property<int>("TongSL")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("IDSP");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IDSPCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaSP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IDHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KichThuoc");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MauSac");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MoTa");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSPCT");

                    b.HasIndex("IDHang");

                    b.HasIndex("IDSP");

                    b.ToTable("SanPhamChiTiet", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("DateTime")
                        .HasColumnName("NamSinh");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ten");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("UserID");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.GioHang", b =>
                {
                    b.HasOne("App_Data_ClassLib.Models.User", "User")
                        .WithOne("GioHang")
                        .HasForeignKey("App_Data_ClassLib.Models.GioHang", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("App_Data_ClassLib.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data_ClassLib.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany()
                        .HasForeignKey("IDSPCT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.HoaDon", b =>
                {
                    b.HasOne("App_Data_ClassLib.Models.User", "User")
                        .WithMany("HoaDons")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("App_Data_ClassLib.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChitiets")
                        .HasForeignKey("IDHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data_ClassLib.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDonChitiets")
                        .HasForeignKey("IDKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data_ClassLib.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany()
                        .HasForeignKey("IDSPCT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("App_Data_ClassLib.Models.Hang", "Hang")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data_ClassLib.Models.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.Hang", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChitiets");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDonChitiets");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data_ClassLib.Models.User", b =>
                {
                    b.Navigation("GioHang")
                        .IsRequired();

                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
